version: "3.2"

services:
  mid-server:
    image: moers/mid-server:madrid
    hostname: mid-madrid
    env_file: mid.env
    volumes: ["./logs:/opt/agent/logs"]
    networks:
      - backend

  cicd:
    image: sn-cicd-example
    build: .
    env_file: .env
    ports:
      - 8080:8080
      - 8443:8443
      # websocket
      - 4443:4443
    volumes:
      - "./root:/opt/cicd"
      # don't do this in prod!
      - "~/.ssh:/home/node/.ssh"
    networks:
      - backend

#  mongo:
#    container_name: mongo
#    image: mongo
#    restart: always
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=passwd
#      - MONGO_NON_ROOT_USERNAME=cicd
#      - MONGO_NON_ROOT_PASSWORD=passwd
#    volumes:
#      - ./root/mongo:/data/db
#      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#    networks:
#     - backend

networks:
  backend:
