version: "3.2"

services:
  mid-server:
    image: moers/mid-server:madrid
    env_file: mid.env
    volumes: ["./logs:/opt/agent/logs"]
    networks:
      - backend

  cicd:
    image: sn-cicd-example
    build: .
    env_file: .env
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - "./root:/opt/cicd"
      # dont use this in prod
      - "~/.ssh:/home/node/.ssh"
    networks:
      - backend

networks:
  backend:
